### PR TITLE
Fix appveyor build, provide instructions for scripthookv sdk extraction.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
The appveyor build is now working, for a successful build see for instance: https://ci.appveyor.com/project/mcmtroffaes/gta5-extended-video-export/build/1.0.23 To enable appveyor for your repository, you'll have to enable it (see https://www.appveyor.com/docs/).

In time we can probably create a zip release package for distribution directly from appveyor as an artifact.

Notes:

* For some reason appveyor refuses to download the sdk from the usual website, so I've picked the one from crosire's website (which crosire uses for compiling the .NET bindings on appveyor). Maybe we should check if Alexander Blade would be ok with a nuget package instead say on nuget.org - that would be more "official" and also easier to incorporate.
* Whilst at it, I've removed the sdk header files: the sdk comes with a readme which seems to prohibit redistribution of these files, and folks need to download the sdk anyway to get the lib file.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
I've just added a commit which creates a zip file for release. You can check out the result here:

https://ci.appveyor.com/project/mcmtroffaes/gta5-extended-video-export/build/1.0.35/artifacts

and the full log:

https://ci.appveyor.com/project/mcmtroffaes/gta5-extended-video-export/build/1.0.35

**Comment by mcmtroffaes** [comment]
Thanks very much for the merge! Could you enable appveyor for this repository? This will enable new builds to be kicked off for every pull request, which is quite useful to spot any unexpected errors, and also then we can use the produced zip file for other people to test without having to ask them to compile it themselves, which is pretty neat. IIRC, what needs to be done to enable it:

* go to https://ci.appveyor.com/login & login by selecting the github option
* click "new project"
* then select the project from the list under "github" and it should be good to go

**Comment by ali-alidoust** [comment]
Thank you for your contributions, friend. I enabled Appveyor as you said.
I'm really learning new things from your commits and I'm happy about it.
I'm currently a bit busy with my job. I'll resume my activity in a few days.

**Comment by mcmtroffaes** [comment]
Thanks very much. The current build on appveyor is crashing in-game, but I'm looking to have this resolved ASAP. Then it's testing and if all is working then I think we can push a new release. I'm sure we can also ask some people on gta5-mods to help testing before the official release.

**Pull request merged**
